# Generated by Django 4.1.1 on 2022-11-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_album_artist_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='music.song'),
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
