# Generated by Django 4.1.1 on 2022-11-21 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist_song_delete_playlistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
