# Generated by Django 4.1.1 on 2022-11-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_album_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='rules',
        ),
        migrations.AddField(
            model_name='playlist',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
