# Generated by Django 4.1.1 on 2022-11-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_playlist_rules_playlist_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
