# Generated by Django 4.1.1 on 2022-11-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_playlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(default=[], to='music.song'),
        ),
    ]
