# Generated by Django 4.1.1 on 2022-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_playlist_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
