# Generated by Django 4.1.1 on 2022-11-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_playlist_cover_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
