# Generated by Django 4.1.1 on 2022-11-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_song_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='image',
            new_name='cover',
        ),
    ]
