# Generated by Django 4.1.1 on 2022-11-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
