# Generated by Django 4.1.1 on 2022-11-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_song_ispublic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='isPublic',
        ),
    ]
