# Generated by Django 4.1.1 on 2022-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_customuser_walletaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='isMint',
            field=models.BooleanField(default=False),
        ),
    ]
