# Generated by Django 4.1.1 on 2022-12-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_album_ismint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='walletAddress',
        ),
    ]
