# Generated by Django 4.1.1 on 2022-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_alter_album_user_alter_artist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web3user',
            name='none',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
