# Generated by Django 4.1.1 on 2022-12-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_alter_album_user_alter_artist_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Web3User',
        ),
        migrations.AddField(
            model_name='customuser',
            name='none',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
