# Generated by Django 4.1.1 on 2022-12-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_delete_web3user_customuser_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='none',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
