# Generated by Django 4.1.1 on 2022-12-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_alter_customuser_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
