# Generated by Django 4.1.1 on 2023-01-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_alter_artist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(null=True, to='music.artist'),
        ),
    ]
